# Generated by Django 2.1.7 on 2020-01-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191230_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='score',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name="Moderator 'score'. Can include letters. For fun."),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_score_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
